# Generated by Django 4.1.2 on 2023-05-08 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Asklepios', '0004_uploadimage_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
